name: Sample - .NET Framework

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  sample-netfx:
    name: Sample - .NET Framework
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\samples\basic\NetFramework\
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          fetch-depth: 0 # depth is needed for nbgv

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          global-json-file: global.json

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('global.json', '**/*.csproj', '**/Directory.*.props', 'NuGet.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ hashFiles('global.json') }}-

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Setup NuGet
        uses: nuget/setup-nuget@323ab0502cd38fdc493335025a96c8fdb0edc71f # v2.0.1

      - name: Restore Packages
        run: msbuild Console.sln -t:Restore

      - name: Build solution
        run: msbuild Console.sln -t:Rebuild

      - name: Run Console
        run: .\Console\bin\Debug\Console.NetFramework.exe
