name: Source Generator Tests

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string
      dotnet-sdk:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test-source-generator:
    name: Source Generator Tests
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          fetch-depth: 0 # depth is needed for nbgv

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-sdk }}

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ inputs.dotnet-sdk }}-${{ hashFiles('**/*.csproj', '**/Directory.*.props', 'NuGet.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ inputs.dotnet-sdk }}-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Mediator.SourceGenerator.Tests
        run: dotnet build --no-restore -v m ./test/Mediator.SourceGenerator.Tests/

      - name: Test Mediator.SourceGenerator.Tests
        run: |
          dotnet test --no-restore --no-build \
            --logger "console;verbosity=detailed" ./test/Mediator.SourceGenerator.Tests/
